### ISSUE TITLE
Size Adjustment?

### ISSUE THREAD

**Issue by ts-han** [utterance/utterances#160]
Hello, 
Is there a way to adjust size of utterances?

Thank yoy  :)

**Comment by summerandwinter** [comment]
awesome

**Comment by jmau111** [comment]
@ts-han @summerandwinter I use this : 

```css
 .utterances {
      max-width: 100%;
 }
```
