### ISSUE TITLE
Loading gif -- before the comment iframe loaded

### ISSUE THREAD

**Issue by rizkysyaiful** [utterance/utterances#198]
This is the one of the last two things that Utterances needs to beat Disqus & friends.

**Comment by Jakeler** [comment]
For now i use the trick with a loading icon in the background, after the iframe is rendered it is invisible, because the comment block is on top. Like this in HTML:
```html
<p class="comments">
    <svg class="loading">
        <use xlink:href="/static/fontawesome/solid.svg#spinner"></use>
    </svg>
    <script src="https://utteranc.es/client.js" ... >
    </script>
</p>
```
And in SASS/CSS:
```css
p.comments {
  position: relative;

  div.utterances {
    position: absolute;
    top: 0;
  }
  
  svg.loading {
    display: block;
    z-index: -1;
    min-height: 10em;
    margin: auto;
    animation: spin infinite 1s;
  }
  
  @keyframes spin {
    from {transform:rotate(0deg);}
    to {transform:rotate(360deg);}
  }
}
```
You can see the result on my blog, for example here: https://blog.ja-ke.tech/about/
