### ISSUE TITLE
[feature request] make dark/light mode change with website theme

### ISSUE THREAD

**Issue by orangemn6** [utterance/utterances#427]
so my website has a light and dark theme. would there be a way to do what the title says?

**Comment by TysonMN** [comment]
Yes.  I am doing so on [my blog](https://tysonwilliams.coding.blog/).

**Comment by orangemn6** [comment]
@TysonMN how would I go about doing this?

**Comment by TysonMN** [comment]
I don't know.  I depends on your website.

**Comment by orangemn6** [comment]
it is built with hugo

**Comment by TysonMN** [comment]
Never heard of it. Sorry.

**Comment by brennerm** [comment]
@orangemn6 Add two elements to your page, each with a unique ID, e.g. "dark-mode" and "light-mode". Both elements have the Utterances script as a child with different values for the theme attribute. On dark/light mode switch you hide one element (display: none;) and show the other (display: block;).
```
        <div id="light-mode">
            <script src="https://utteranc.es/client.js"
                repo="$REPO"
                issue-term="pathname"
                theme="github-light"
                crossorigin="anonymous"
                async>
            </script>
        </div>
        <div id="dark-mode">
            <script src="https://utteranc.es/client.js"
                repo="$REPO"
                issue-term="pathname"
                theme="github-dark"
                crossorigin="anonymous"
                async>
            </script>
        </div>
```

Here you can find the relevant code of my blog.
https://github.com/brennerm/brennerm.github.io/blob/gh-pages/static/js/application.js#L64
https://github.com/brennerm/brennerm.github.io/blob/gh-pages/_layouts/post.html#L25

**Comment by orangemn6** [comment]
@brennerm I like that idea! I am trying to make an if statement now

**Comment by orangemn6** [comment]
@brennerm for me the script is loaded twice on top of each other? is this supposed to happen?

**Comment by TysonMN** [comment]
That is the behavior on [my blog](https://tysonwilliams.coding.blog/2020-12-01_csharp_task_to_fsharp_async).  I don't see a benefit in trying to optimize this.

**Comment by brennerm** [comment]
@orangemn6 Do you mean on my blog?

**Comment by orangemn6** [comment]
@brennerm yes

**Comment by brennerm** [comment]
Mmh that's strange. Had another look at it and switched to a CSS based logic. Below you can find my rules.

```css
html[data-theme="dark"] #utterances-light {
    display: none;
}

html[data-theme="dark"] #utterances-dark {
    display: block;
}

html #utterances-light,
html[data-theme="light"] #utterances-light {
    display: block;
}

html #utterances-dark,
html[data-theme="light"] #utterances-dark {
    display: none;
}
```

Please let me know if that works for you.
