### ISSUE TITLE
Why I can not use utterances in my blog site

### ISSUE THREAD

**Issue by kands-code** [utterance/utterances#489]
I'm using hexo with the theme "NeXT" to be my blog. When I want to add a comment system to my blog, I have chosen "utterance". But I find that it is not work on my blog site.

my config:
```yaml _config.next.yaml
utterances:
  enable: true
  repo: kands-code.github.io
  issue_term: pathname
  theme: github-light
```
and when I preview my blog, I can find the js file is loaded.

![图片](https://user-images.githubusercontent.com/59006329/108176408-f528cb80-713c-11eb-9de1-70e741325270.png)
![图片](https://user-images.githubusercontent.com/59006329/108176513-14275d80-713d-11eb-996d-51c90ea01cae.png)

but I can't see it.
