### ISSUE TITLE
Suggest template names for static generators

### ISSUE THREAD

**Issue by coolaj86** [utterance/utterances#552]
Hugo, Zola, Gatsby, etc.

If you suggest what variable names to use, then all of the themes will likely converge on the same thing. If not, they'll all create their own.

Here are my suggestions:

# For Sites

```yaml
# github_issues_repo: '<owner>/<project>'
# Example:
github_issues_repo: devloper/wuph
utterences_term: pathname
```

I specify `github_issues_repo` so that it's clear as to why it's not a full URL, and that if at some point `gitea` and `gitlab` are supported, the name won't need to change.

# For Pages

```yaml
---
title: "Article Title - Updated for 2021"
description: "A great article"
utterences_term: "Original Article Title"
---
```

So that the title of the page can be changed without affecting which issue it is associated with.

With that I'd also make the suggestion that if the utterences term is less than 8 characters and doesn't contain spaces that utterences also include the title. That way I could use a random ID that's permanent but still have the issue title make sense.
